package com.gm.hrms.enums;

public enum ErrorCode {

    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    BAD_REQUEST
}
